version: "3.2"

services: 
  redis:
    image: redis

  hubot:
    image: linuxbandit/hubot
    restart: on-failure
    env_file:
      - .env
    environment: 
      REDIS_URL: redis
      HUBOT_SLACK_TOKEN: ${HUBOT_SLACK_TOKEN}
      EXTRA_PACKAGES: "hubot-auth,hubot-github-deployments"
      HUBOT_AUTH_ADMIN: "U42J1D214"
