name: deploy 

on:
  repository_dispatch: 
    types: [deploy-service]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - env:
          MESSAGE: ${{ github.event.client_payload.message }}
        run: echo $MESSAGE
