name: Env Deployment

on:
  push:
    branches:
      - temp1

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: 
      name: temp1
      url: https://github.com
    steps:
      - name: deploy
        run: echo 1
